/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quantacast;

import com.quantacast.configuration.ApplicationArgumentParser;
import com.quantacast.configuration.ArgumentParser;
import com.quantacast.service.CookieProcessingService;
import com.quantacast.service.CookieProcessingServiceImpl;

import org.apache.commons.cli.ParseException;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Collection;

public class App {

    public static void main(String[] args) {
        ArgumentParser parser = null;
        try {
            parser = new ApplicationArgumentParser(args);
        } catch (ParseException e) {
            e.printStackTrace();
            System.exit(-1);
        }

        try {
            File inputFile = parser.getInputFile();
            LocalDate localDate = parser.getDate();

            CookieProcessingService cookieProcessingService = new CookieProcessingServiceImpl(inputFile, localDate);
            Collection<String> mostUsedCookies = cookieProcessingService.findMostUsedCookies();
            for (String cookie : mostUsedCookies) {
                System.out.println(cookie);
            }
        } catch (FileNotFoundException e) {
            System.err.println("File not found " + e.getMessage());
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }
}
